# Minimum/maximum values for timestamp.
# If found number exceeds them, it will not be considered a valid timestamp.
# timestamp_min can be up to 10 characters long (0-9999999999)
timestamp_min: 100000000 # 1973-03-03
# timestamp_max can be up to 11 characters long (0-99999999999)
timestamp_max: 7258111200 # 2200-01-01

# If enabled, text in the statusbar will be cleared after copying anything else
clear_on_change: false

# Automatically clear text in the status bar after this time, in seconds.
# 0 or less to disable automatic clearing.
clear_after_time: 300

# Supported only on Linux, ignored on macOS # TODO
update_on_highlight: true # TODO

# If enabled, will shortly flash status bar icon on timestamp change
flash_icon_on_change: true

clipboard_polling: false # TODO

# Interval in seconds for clipboard polling to find changed content.
# Has no effect when on Linux and clipboard polling is disabled.
clipboard_polling_interval: 0.33

# Formatting template for main text on the statusbar.
# Will use first template found where key is less than relative time difference
# in seconds.
#
# Templates must be ordered ascending by time difference in their key.
#
# Templates support all standard strftime() codes:
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
# and these custom codes for relative time:
# - {ts} - unix timestamp. Milliseconds will be separated by for better readability.
# - {ts_ms} - unix timestamp. Milliseconds won't be separated to allow copying a valid timestamp.
# - {r_int} - relative time with integer number, e.g. '5 h ago'.
# - {r_float} - relative time with float number, e.g. '5.5 h ago'.
format_icon:
    # Up to 60 s, e.g. "1619295908 - 59 s ago"
    60: "{ts} - {r_int}"
    # Up to 10 min, e.g. "1619295908 - 5 min ago"
    600: "{ts} - {r_int}"
    # Up to 1 h, e.g. "1619295908 - 29 min ago (15:10)"
    3600: "{ts} - {r_float} (%H:%M)"
    # Up to 1 day, e.g. "1619295908 - 5.5 h ago (12:00)"
    86400: "{ts} - {r_float} (%H:%M)"
    # Up to 1 month, e.g. "1619295908 - 5.5 days ago (08-05 12:00)"
    2678400: "{ts} - {r_float} (%m-%d  %H:%M)"
    # Up to 1 year, e.g. "1619295908 - 9.2 months ago"
    31536000: "{ts} - {r_float}"
    # Up to 75 years, e.g. "1619295908 - 5.8 years ago ('15)"
    2365200000: "{ts} - {r_float} ('%y)"
    # Default if no other format matches, e.g. "1619295908 - 420 years ago"
    # Must be last element in the list
    default: "{ts} - {r_float}"

# Formatting template to use for menu items under "Last timestamp".
# Supports the same formats as in "format_icon" configuration.
menu_items_last_timestamp:
    Last timestamp: "{ts_ms}"
    Last datetime: "%Y-%m-%d %H:%M:%S"

# Formatting template to use for menu items under "Current timestamp".
# Supports the same formats as in "format_icon" configuration.
menu_items_current_timestamp:
    Current timestamp: "{ts_ms}"
    Current datetime: "%Y-%m-%d %H:%M:%S"

# If enabled, will log additional info to the console
debug: false
